apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
  labels:
    app: task-manager-load-balancer
spec:
  selector:
    app: task-manager-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
