apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-candidate
  labels:
    app: release-candidate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: release-candidate
  template:
    metadata:
      labels:
        app: release-candidate
    spec:
      containers:
      - name: task-manager-api
        image: 490300663378.dkr.ecr.us-east-2.amazonaws.com/task-manager-api:latest
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: prod-env
